const SCREEN_ROUTER = {
  MAIN: "Main",
  AUTH: "Auth",
  HOME: "Home",
  LOGIN: "Login",
  AUTH_LOADING: "AuthLoading",
  FORGOT_PASS: "ForgotPassword",
  REGISTER: "Register",
  USER: "User",
  TO_DO: "ToDo",
  CHAR_PIE: "CharPie",
  PRODUCT: "Product",
  CHAT: "Chat",
  ROOM_CHAT: "RoomChat",
  WORK: "Work",
  BOTTOM_BAR: "BottomBar",
  ADD_MOVIES: "AddMovies",
  ADD_PRODUCTS: "AddProducts",
  ADD_IMAGE_MOVIES: "AddImageMovies",
  ADD_IMAGE_PRODUCTS: "AddImageProducts",
  MOVIES_CURRENT: "MoviesCurrent",
  PRODUCTS_CURRENT: "ProductCurrent",
};

export { SCREEN_ROUTER };
